# Generated by Django 4.2.27 on 2026-02-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image_home', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('nom_produit', models.CharField(max_length=200)),
                ('type_produit', models.CharField(max_length=100)),
                ('puissance', models.CharField(blank=True, max_length=50)),
                ('tension_nominal', models.CharField(blank=True, max_length=50)),
                ('courrant', models.CharField(blank=True, max_length=50)),
                ('longeur', models.CharField(blank=True, max_length=50)),
                ('voltage', models.CharField(blank=True, max_length=50)),
                ('date_mise_sur_marche', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Yaskawa_app_bckend.category')),
            ],
        ),
    ]
