# Generated by Django 5.2.11 on 2026-02-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaskawa_app_bckend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reference',
            new_name='model_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nom_produit',
            new_name='numero_SAP',
        ),
        migrations.RemoveField(
            model_name='product',
            name='courrant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='longeur',
        ),
        migrations.RemoveField(
            model_name='product',
            name='puissance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tension_nominal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='voltage',
        ),
        migrations.AddField(
            model_name='product',
            name='caracteristique',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
