# Generated by Django 5.2.11 on 2026-02-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaskawa_app_bckend', '0002_rename_reference_product_model_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caracteristique',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_produit',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_mise_sur_marche',
        ),
        migrations.AddField(
            model_name='product',
            name='compatible',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='usable_with',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
