# Generated by Django 5.2.11 on 2026-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaskawa_app_bckend', '0003_rename_caracteristique_product_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='usable_with',
            field=models.CharField(max_length=200),
        ),
    ]
