# Generated by Django 5.2.11 on 2026-02-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaskawa_app_bckend', '0005_alter_product_compatible_alter_product_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='usable_with',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de liaison')),
                ('compatible_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_relations', to='Yaskawa_app_bckend.product', verbose_name='Equipement Compatible')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='Yaskawa_app_bckend.product', verbose_name='Produit Maitre')),
            ],
            options={
                'verbose_name': 'Compatibilité',
                'verbose_name_plural': 'Compatibilités',
                'unique_together': {('source_product', 'compatible_product', 'relation_type')},
            },
        ),
    ]
