# Generated by Django 5.2.12 on 2026-03-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaskawa_app_bckend', '0007_product_compat_range_1_product_compat_range_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('power_kw', models.FloatField(blank=True, null=True)),
                ('voltage', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('encoder_type', models.CharField(blank=True, max_length=20, null=True)),
                ('option', models.CharField(blank=True, max_length=50, null=True)),
                ('specification', models.CharField(blank=True, max_length=50, null=True)),
                ('brake', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='Yaskawa_app_bckend.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
            },
        ),
    ]
