# Generated by Django 5.2.12 on 2026-03-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaskawa_app_bckend', '0008_productspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='families/')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Famille Produit',
                'verbose_name_plural': 'Familles Produit',
                'ordering': ['prefix'],
            },
        ),
    ]
